# Generated by Django 4.0 on 2022-01-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('admission_no', models.CharField(blank=True, max_length=20)),
                ('datetime', models.DateTimeField()),
                ('special_token', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rights', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('poll_topic', models.CharField(max_length=500)),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(blank=True, max_length=500)),
                ('option_4', models.CharField(blank=True, max_length=500)),
                ('submitted', models.CharField(max_length=500)),
                ('leading_option', models.CharField(blank=True, max_length=500)),
                ('datetime', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.CharField(max_length=255, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('special_token', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('course_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255, unique=True)),
                ('subject_code', models.CharField(max_length=255, unique=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('tutorial_number', models.CharField(max_length=255)),
                ('tutorial_question', models.CharField(blank=True, max_length=500)),
                ('tutorial_solution', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='PollSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(max_length=255)),
                ('poll_topic', models.CharField(max_length=500)),
                ('option_selected', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
    ]
