# Generated by Django 4.0 on 2022-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
