# Generated by Django 4.0 on 2022-01-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_admindata_special_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 18, 12, 48, 165325)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_question',
            field=models.FileField(blank=True, upload_to='tutorial_questions/'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_solution',
            field=models.FileField(upload_to='tutorial_solutions/'),
        ),
    ]
