# Generated by Django 4.0 on 2022-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_polls_end_datetime_alter_tutorials_tutorial_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='poll_id',
        ),
        migrations.AddField(
            model_name='polls',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
