# Generated by Django 4.0 on 2022-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_polls_poll_id_polls_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='poll_slug',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=500),
        ),
    ]
