# Generated by Django 4.0 on 2022-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_polls_poll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
