# Generated by Django 4.0 on 2022-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_students_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
